### KNN Classifier

In [40]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor
from sklearn.preprocessing import StandardScaler,LabelEncoder,MinMaxScaler

In [2]:
data=pd.read_csv('healthcare-dataset-stroke-data.csv')

In [3]:
data

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,Female,80.0,1,0,Yes,Private,Urban,83.75,NaN,never smoked,0
5106,44873,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0
5107,19723,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0
5108,37544,Male,51.0,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0
5109,44679,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0

In [5]:
data.isnull().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [9]:
import math
bmi_mean=data['bmi'].mean()
bmi_mean=math.ceil(bmi_mean)
bmi_mean

29

In [11]:
data['bmi']=data.bmi.fillna(bmi_mean)

In [12]:
data.isnull().sum()

id                   0
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [15]:
gen=LabelEncoder()
data['gender']=gen.fit_transform(data.gender)

married=LabelEncoder()
data['ever_married']=married.fit_transform(data['ever_married'])

work=LabelEncoder()
data['work_type']=work.fit_transform(data['work_type'])

residence=LabelEncoder()
data['Residence_type']=residence.fit_transform(data['Residence_type'])

smoking=LabelEncoder()
data['smoking_status']=smoking.fit_transform(data['smoking_status'])

In [16]:
data

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,1,67.0,0,1,1,2,1,228.69,36.6,1,1
1,51676,0,61.0,0,0,1,3,0,202.21,29.0,2,1
2,31112,1,80.0,0,1,1,2,0,105.92,32.5,2,1
3,60182,0,49.0,0,0,1,2,1,171.23,34.4,3,1
4,1665,0,79.0,1,0,1,3,0,174.12,24.0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,0,80.0,1,0,1,2,1,83.75,29.0,2,0
5106,44873,0,81.0,0,0,1,3,1,125.20,40.0,2,0
5107,19723,0,35.0,0,0,1,3,0,82.99,30.6,2,0
5108,37544,1,51.0,0,0,1,2,0,166.29,25.6,1,0
5109,44679,0,44.0,0,0,1,0,1,85.28,26.2,0,0

In [17]:
data=data.drop('id',axis=1)

In [18]:
data

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,1,67.0,0,1,1,2,1,228.69,36.6,1,1
1,0,61.0,0,0,1,3,0,202.21,29.0,2,1
2,1,80.0,0,1,1,2,0,105.92,32.5,2,1
3,0,49.0,0,0,1,2,1,171.23,34.4,3,1
4,0,79.0,1,0,1,3,0,174.12,24.0,2,1
...,...,...,...,...,...,...,...,...,...,...,...
5105,0,80.0,1,0,1,2,1,83.75,29.0,2,0
5106,0,81.0,0,0,1,3,1,125.20,40.0,2,0
5107,0,35.0,0,0,1,3,0,82.99,30.6,2,0
5108,1,51.0,0,0,1,2,0,166.29,25.6,1,0
5109,0,44.0,0,0,1,0,1,85.28,26.2,0,0

In [19]:
x=data.drop("stroke",axis=1)
y=data['stroke']

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=90)

In [22]:
model1=KNeighborsClassifier(n_neighbors=20)

In [23]:
model1.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=20)

In [24]:
model1.score(x_test,y_test)

0.9546165884194053

In [25]:
#Standard Scaler
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [26]:
model2=KNeighborsClassifier(n_neighbors=20)
model2.fit(x_train_scaled,y_train)

KNeighborsClassifier(n_neighbors=20)

In [27]:
model2.score(x_test_scaled,y_test)

0.9546165884194053

In [28]:
#Minmax Scaler
scaler2=MinMaxScaler()
x_train_scaled=scaler2.fit_transform(x_train)
x_test_scaled=scaler2.transform(x_test)

In [29]:
model3=KNeighborsClassifier(n_neighbors=20)
model3.fit(x_train_scaled,y_train)

KNeighborsClassifier(n_neighbors=20)

In [30]:
model3.score(x_test_scaled,y_test)

0.9546165884194053

### KNN Regressor

In [31]:
data=pd.read_csv('Admission_Predict.csv')

In [32]:
data

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65
...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91
398,399,312,103,3,3.5,4.0,8.78,0,0.67
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [33]:
data.drop('Serial No.',axis=1)

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,337,118,4,4.5,4.5,9.65,1,0.92
1,324,107,4,4.0,4.5,8.87,1,0.76
2,316,104,3,3.0,3.5,8.00,1,0.72
3,322,110,3,3.5,2.5,8.67,1,0.80
4,314,103,2,2.0,3.0,8.21,0,0.65
...,...,...,...,...,...,...,...,...
395,324,110,3,3.5,3.5,9.04,1,0.82
396,325,107,3,3.0,3.5,9.11,1,0.84
397,330,116,4,5.0,4.5,9.45,1,0.91
398,312,103,3,3.5,4.0,8.78,0,0.67
399,333,117,4,5.0,4.0,9.66,1,0.95

In [35]:
data.columns

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [36]:
data.isnull().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [38]:
x=data.drop('Chance of Admit ',axis=1)
y=data['Chance of Admit ']

In [39]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=6)

In [41]:
model1=KNeighborsRegressor()

In [42]:
model1.fit(x_train,y_train)

KNeighborsRegressor()

In [43]:
model1.score(x_test,y_test)

0.751068806876361

In [45]:
#Standard Scaler
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [46]:
model2=KNeighborsRegressor(n_neighbors=20)
model2.fit(x_train_scaled,y_train)
model2.score(x_test_scaled,y_test)

0.7547198546272662

In [47]:
#Minmax
scaler2=MinMaxScaler()
x_train_scaled=scaler2.fit_transform(x_train)
x_test_scaled=scaler2.transform(x_test)

In [49]:
model3=KNeighborsRegressor(n_neighbors=20)
model3.fit(x_train_scaled,y_train)
model3.score(x_test_scaled,y_test)

0.7476515380954443